--- 
title: "behaviouR: R package and tutorials for teaching of fundamental concepts in behavior and ecology"
author: "Dena J. Clink"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: 'DenaJGibbon/behaviouRtutorials'
description: "This is the location for all of the tutorials associated with the behaviouR R package."
cover-image: 'images/titlepage.pdf'
---

# Welcome {-}
```{r echo=FALSE,fig.align='center',warning=FALSE,message=FALSE}
library(behaviouR)
library(tuneR)
library(seewave)
library(stringr)
library(plyr)
library(ggplot2)
library(ggfortify)
library(ggpubr)

# Lab 1 figures
deerImage <- magick::image_read('images/Red_deer_stag.jpg')
deerImage <-magick::image_ggplot(deerImage)

deerImage <-deerImage + theme(panel.border = element_rect(colour = "white", fill=NA, size=20))

data("MaleDeerRoarDF")

Fig1b <- ggbarplot(MaleDeerRoarDF, x='MaleCategory', y='RoarsPerMinute', fill = 'MaleCategory',
          palette = c('red','gray','white','black'),
          add = c("mean_se"))+ theme(legend.position = "none")+theme(text = element_text(size=10))



MaleRedDeerDF <- CorrelatedDataSimulationFunction(N=100, 
                                                  CorrelationCoefficient= 0.45,
                                                  MaleMeanBodyWeight = 125,
                                                  MaleReproductiveSuccess = 3)

Fig1c <- ggscatter(data=MaleRedDeerDF,x='MaleBodyWeight',y='MaleReproductiveSuccess',
          add='reg.line')+xlab('Male Body Weight (kg)')+ylab('Male Reproductive Success')


data("DeerSpeciesAcousticFeatures")
DeerSpeciesAcousticFeaturesPCA <- princomp(DeerSpeciesAcousticFeatures[,-c(4)])
Fig1d <- ggplot2::autoplot(DeerSpeciesAcousticFeaturesPCA, data = DeerSpeciesAcousticFeatures, colour = 'Class',
         loadings = FALSE, loadings.colour = 'red',
         loadings.label = FALSE,
         loadings.label.size = 5)+theme_bw()+scale_color_manual(values = c('red','gray','black'))

print(cowplot::plot_grid(deerImage,Fig1b,
                   Fig1c, Fig1d,labels = c('A','B','C','D'),label_x = .92))

```

To get started you should download the package from Github using the following code.
```{r, eval=FALSE}
# Install devtools from CRAN
install.packages("devtools")

# Install 'behaviouR' package from Gitub
devtools::install_github("https://github.com/DenaJGibbon/behaviouR")

```

Note: If you have never used R before I highly recommend that you check out the primers here: https://rstudio.cloud/learn/primers. 

You can navigate using the tabs at the left and/or the arrows.
