<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Lab 3. Analyzing Acoustic Data | behaviouR: R package and tutorials for online teaching of fundamental concepts in behavior and ecology</title>
  <meta name="description" content="This is the location for all of the tutorials associated with the behaviouR R package." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Lab 3. Analyzing Acoustic Data | behaviouR: R package and tutorials for online teaching of fundamental concepts in behavior and ecology" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the location for all of the tutorials associated with the behaviouR R package." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Lab 3. Analyzing Acoustic Data | behaviouR: R package and tutorials for online teaching of fundamental concepts in behavior and ecology" />
  
  <meta name="twitter:description" content="This is the location for all of the tutorials associated with the behaviouR R package." />
  

<meta name="author" content="Dena J. Clink" />


<meta name="date" content="2020-08-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lab-2-activity-budgets-and-ethograms.html"/>
<link rel="next" href="lab-4-vigilance-behavior.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BioNBB 2210 Summer 2020 Computer Labs</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="lab-1-data-exploration-and-visualization.html"><a href="lab-1-data-exploration-and-visualization.html"><i class="fa fa-check"></i><b>1</b> Lab 1. Data exploration and visualization</a><ul>
<li class="chapter" data-level="" data-path="lab-1-data-exploration-and-visualization.html"><a href="lab-1-data-exploration-and-visualization.html#lab-1a.-categorical-data"><i class="fa fa-check"></i>Lab 1a. Categorical data</a></li>
<li class="chapter" data-level="" data-path="lab-1-data-exploration-and-visualization.html"><a href="lab-1-data-exploration-and-visualization.html#lab-1b.-categorical-and-continuous-data"><i class="fa fa-check"></i>Lab 1b. Categorical and continuous data</a></li>
<li class="chapter" data-level="" data-path="lab-1-data-exploration-and-visualization.html"><a href="lab-1-data-exploration-and-visualization.html#lab-1c.-categorical-and-continuous-data"><i class="fa fa-check"></i>Lab 1c. Categorical and continuous data</a></li>
<li class="chapter" data-level="" data-path="lab-1-data-exploration-and-visualization.html"><a href="lab-1-data-exploration-and-visualization.html#lab-1d.-multivariate-data"><i class="fa fa-check"></i>Lab 1d. Multivariate data</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="lab-2-activity-budgets-and-ethograms.html"><a href="lab-2-activity-budgets-and-ethograms.html"><i class="fa fa-check"></i><b>2</b> Lab 2. Activity Budgets and Ethograms</a><ul>
<li class="chapter" data-level="" data-path="lab-2-activity-budgets-and-ethograms.html"><a href="lab-2-activity-budgets-and-ethograms.html#lab-2a.-enter-and-visualize-your-ethogram-data"><i class="fa fa-check"></i>Lab 2a. Enter and visualize your ethogram data</a></li>
<li class="chapter" data-level="" data-path="lab-2-activity-budgets-and-ethograms.html"><a href="lab-2-activity-budgets-and-ethograms.html#lab-2b.-calculate-meerkat-activity-budgets."><i class="fa fa-check"></i>Lab 2b. Calculate meerkat activity budgets.</a></li>
<li class="chapter" data-level="" data-path="lab-2-activity-budgets-and-ethograms.html"><a href="lab-2-activity-budgets-and-ethograms.html#lab-2c.-scan-sampling-and-inter-observer-reliability."><i class="fa fa-check"></i>Lab 2c. Scan sampling and inter-observer reliability.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lab-3-analyzing-acoustic-data.html"><a href="lab-3-analyzing-acoustic-data.html"><i class="fa fa-check"></i><b>3</b> Lab 3. Analyzing Acoustic Data</a><ul>
<li class="chapter" data-level="" data-path="lab-3-analyzing-acoustic-data.html"><a href="lab-3-analyzing-acoustic-data.html#part-1.-loading-a-sound-file-and-making-a-spectrogram"><i class="fa fa-check"></i>Part 1. Loading a sound file and making a spectrogram</a></li>
<li class="chapter" data-level="" data-path="lab-3-analyzing-acoustic-data.html"><a href="lab-3-analyzing-acoustic-data.html#part-2.-visualizing-differences-in-gibbon-and-great-argus-calls"><i class="fa fa-check"></i>Part 2. Visualizing differences in gibbon and great argus calls</a></li>
<li class="chapter" data-level="" data-path="lab-3-analyzing-acoustic-data.html"><a href="lab-3-analyzing-acoustic-data.html#part-3.-soundscapes"><i class="fa fa-check"></i>Part 3. Soundscapes</a></li>
<li class="chapter" data-level="" data-path="lab-3-analyzing-acoustic-data.html"><a href="lab-3-analyzing-acoustic-data.html#part-4.-now-it-is-time-to-analyze-the-data-you-collected-for-this-weeks-field-lab."><i class="fa fa-check"></i>Part 4. Now it is time to analyze the data you collected for this week’s field lab.</a><ul>
<li class="chapter" data-level="3.0.1" data-path="lab-3-analyzing-acoustic-data.html"><a href="lab-3-analyzing-acoustic-data.html#part-4a.-your-focal-recordings"><i class="fa fa-check"></i><b>3.0.1</b> Part 4a. Your focal recordings</a></li>
<li class="chapter" data-level="3.0.2" data-path="lab-3-analyzing-acoustic-data.html"><a href="lab-3-analyzing-acoustic-data.html#part-4b.-soundscape-recordings"><i class="fa fa-check"></i><b>3.0.2</b> Part 4b. Soundscape recordings</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lab-4-vigilance-behavior.html"><a href="lab-4-vigilance-behavior.html"><i class="fa fa-check"></i><b>4</b> Lab 4. Vigilance behavior</a><ul>
<li class="chapter" data-level="4.1" data-path="lab-4-vigilance-behavior.html"><a href="lab-4-vigilance-behavior.html#part-1-barnacle-goose-vigilance"><i class="fa fa-check"></i><b>4.1</b> Part 1: Barnacle goose vigilance</a><ul>
<li class="chapter" data-level="4.1.1" data-path="lab-4-vigilance-behavior.html"><a href="lab-4-vigilance-behavior.html#part-1a-surveillance-behavior"><i class="fa fa-check"></i><b>4.1.1</b> Part 1a: Surveillance behavior</a></li>
<li class="chapter" data-level="4.1.2" data-path="lab-4-vigilance-behavior.html"><a href="lab-4-vigilance-behavior.html#part-1b-time-vigilant-secmin"><i class="fa fa-check"></i><b>4.1.2</b> Part 1b: Time vigilant (sec/min)</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="lab-4-vigilance-behavior.html"><a href="lab-4-vigilance-behavior.html#part-2-meerkat-data-revisted"><i class="fa fa-check"></i><b>4.2</b> Part 2: Meerkat data revisted</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lab-5-estimating-population-density-and-biodiversity.html"><a href="lab-5-estimating-population-density-and-biodiversity.html"><i class="fa fa-check"></i><b>5</b> Lab 5. Estimating Population Density and Biodiversity</a><ul>
<li class="chapter" data-level="5.1" data-path="lab-5-estimating-population-density-and-biodiversity.html"><a href="lab-5-estimating-population-density-and-biodiversity.html#part-1.-population-density-estimation."><i class="fa fa-check"></i><b>5.1</b> Part 1. Population density estimation.</a></li>
<li class="chapter" data-level="5.2" data-path="lab-5-estimating-population-density-and-biodiversity.html"><a href="lab-5-estimating-population-density-and-biodiversity.html#part-2.-comparing-biodiversity."><i class="fa fa-check"></i><b>5.2</b> Part 2. Comparing biodiversity.</a><ul>
<li class="chapter" data-level="5.2.1" data-path="lab-5-estimating-population-density-and-biodiversity.html"><a href="lab-5-estimating-population-density-and-biodiversity.html#alpha-diversity."><i class="fa fa-check"></i><b>5.2.1</b> Alpha diversity.</a></li>
<li class="chapter" data-level="5.2.2" data-path="lab-5-estimating-population-density-and-biodiversity.html"><a href="lab-5-estimating-population-density-and-biodiversity.html#beta-diversity."><i class="fa fa-check"></i><b>5.2.2</b> Beta diversity.</a></li>
<li class="chapter" data-level="5.2.3" data-path="lab-5-estimating-population-density-and-biodiversity.html"><a href="lab-5-estimating-population-density-and-biodiversity.html#now-we-will-use-your-partners-data-to-estimate-alpha-diversity"><i class="fa fa-check"></i><b>5.2.3</b> Now we will use your partner’s data to estimate alpha diversity</a></li>
<li class="chapter" data-level="5.2.4" data-path="lab-5-estimating-population-density-and-biodiversity.html"><a href="lab-5-estimating-population-density-and-biodiversity.html#gamma-diversity"><i class="fa fa-check"></i><b>5.2.4</b> Gamma diversity</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="lab-5-estimating-population-density-and-biodiversity.html"><a href="lab-5-estimating-population-density-and-biodiversity.html#part-3.-biodiversity-indices-in-the-real-world."><i class="fa fa-check"></i><b>5.3</b> Part 3. Biodiversity indices in the real world.</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lab-6-analyzing-camera-trap-data-.html"><a href="lab-6-analyzing-camera-trap-data-.html"><i class="fa fa-check"></i><b>6</b> Lab 6. Analyzing camera trap data.</a><ul>
<li class="chapter" data-level="6.1" data-path="lab-6-analyzing-camera-trap-data-.html"><a href="lab-6-analyzing-camera-trap-data-.html#part-1-collect-serengeti-camera-trap-data"><i class="fa fa-check"></i><b>6.1</b> Part 1: Collect Serengeti camera trap data</a></li>
<li class="chapter" data-level="6.2" data-path="lab-6-analyzing-camera-trap-data-.html"><a href="lab-6-analyzing-camera-trap-data-.html#part-2-analyze-your-serengeti-camera-trap-data"><i class="fa fa-check"></i><b>6.2</b> Part 2: Analyze your Serengeti camera trap data</a></li>
<li class="chapter" data-level="6.3" data-path="lab-6-analyzing-camera-trap-data-.html"><a href="lab-6-analyzing-camera-trap-data-.html#part-3-focus-on-your-partners-serengeti-camera-trap-data"><i class="fa fa-check"></i><b>6.3</b> Part 3: Focus on your partner’s Serengeti camera trap data</a></li>
<li class="chapter" data-level="6.4" data-path="lab-6-analyzing-camera-trap-data-.html"><a href="lab-6-analyzing-camera-trap-data-.html#part-4.-investigating-temporal-niche-partitioning-in-four-different-animals"><i class="fa fa-check"></i><b>6.4</b> Part 4. Investigating temporal niche partitioning in four different animals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-1-data-exploration-and-visualization-r-script.html"><a href="appendix-1-data-exploration-and-visualization-r-script.html"><i class="fa fa-check"></i>Appendix 1. Data exploration and visualization R script</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">behaviouR: R package and tutorials for online teaching of fundamental concepts in behavior and ecology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lab-3.-analyzing-acoustic-data" class="section level1">
<h1><span class="header-section-number">3</span> Lab 3. Analyzing Acoustic Data</h1>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-52-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><em>Background</em><br />
In this lab you will become familiar with the ways that we analyze acoustic data. You will start by analyzing focal recordings and soundscapes from Southeast Asia, and you will then upload the data you collected for Field Lab 3 and do some prelminary analysis.</p>
<p><em>Goals of the exercises</em><br />
The main goal(s) of today’s lab are to:<br />
1) Create your own spectrograms<br />
2) Learn how we use PCA to visualize differences in acoustic data<br />
3) Upload and visualize your own data</p>
<p><em>Getting started</em><br />
First we need to load the relevant packages for our data analysis. Packages contain all the functions that are needed for data analysis.
First we load the required libraries</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1"><span class="kw">library</span>(behaviouR)</a></code></pre></div>
<p>We need to do some data prep to work through the examples</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1"><span class="co"># First you can check where your working directory is; this is where R will store the files locally</span></a>
<a class="sourceLine" id="cb65-2" data-line-number="2"><span class="kw">getwd</span>()</a>
<a class="sourceLine" id="cb65-3" data-line-number="3"></a>
<a class="sourceLine" id="cb65-4" data-line-number="4"><span class="co"># Now we will create a file at this location called &#39;FocalRecordings&#39;</span></a>
<a class="sourceLine" id="cb65-5" data-line-number="5"><span class="kw">dir.create</span>(<span class="kw">file.path</span>(<span class="st">&#39;FocalRecordings&#39;</span>), <span class="dt">showWarnings =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb65-6" data-line-number="6"></a>
<a class="sourceLine" id="cb65-7" data-line-number="7"><span class="co"># Now we will load the sound files that were in the R package</span></a>
<a class="sourceLine" id="cb65-8" data-line-number="8"><span class="kw">data</span>(<span class="st">&quot;FocalRecordings&quot;</span>)</a>
<a class="sourceLine" id="cb65-9" data-line-number="9"></a>
<a class="sourceLine" id="cb65-10" data-line-number="10"><span class="co"># Let&#39;s check the structure</span></a>
<a class="sourceLine" id="cb65-11" data-line-number="11"><span class="kw">head</span>(FocalRecordings)</a>
<a class="sourceLine" id="cb65-12" data-line-number="12"></a>
<a class="sourceLine" id="cb65-13" data-line-number="13"><span class="co"># Now we will save the recordings to the new folder you created</span></a>
<a class="sourceLine" id="cb65-14" data-line-number="14"><span class="cf">for</span>(a <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(FocalRecordings)){</a>
<a class="sourceLine" id="cb65-15" data-line-number="15">  FileName &lt;-<span class="st"> </span>FocalRecordings[[a]][<span class="dv">1</span>][[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb65-16" data-line-number="16">  WaveFile &lt;-<span class="st"> </span>FocalRecordings[[a]][<span class="dv">2</span>][[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb65-17" data-line-number="17">  tuneR<span class="op">::</span><span class="kw">writeWave</span>(WaveFile, <span class="kw">paste</span>(<span class="st">&quot;FocalRecordings/&quot;</span>,FileName,<span class="dt">sep=</span><span class="st">&#39;&#39;</span>))</a>
<a class="sourceLine" id="cb65-18" data-line-number="18">}</a></code></pre></div>
<div id="part-1.-loading-a-sound-file-and-making-a-spectrogram" class="section level2 unnumbered">
<h2>Part 1. Loading a sound file and making a spectrogram</h2>
<p>First we want to check which files are in the folder
There are five gibbon female recordings and five great argus recordings.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1"><span class="kw">list.files</span>(<span class="st">&quot;FocalRecordings&quot;</span>)</a></code></pre></div>
<pre><code>##  [1] &quot;FemaleGibbon_1.wav&quot; &quot;FemaleGibbon_2.wav&quot; &quot;FemaleGibbon_3.wav&quot;
##  [4] &quot;FemaleGibbon_4.wav&quot; &quot;GreatArgus_1.wav&quot;   &quot;GreatArgus_2.wav&quot;  
##  [7] &quot;GreatArgus_3.wav&quot;   &quot;GreatArgus_4.wav&quot;   &quot;MaleSolo_1.wav&quot;    
## [10] &quot;MaleSolo_2.wav&quot;     &quot;MaleSolo_3.wav&quot;     &quot;MaleSolo_4.wav&quot;    
## [13] &quot;Thumbnails&quot;</code></pre>
<p>Now let’s read in one of the files for further investigation. We do that with the function ‘readWave’. The .wav stands for ‘Waveform Audio File’ and is a common format that scientists use to save their sound files.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1">GibbonWaveFile &lt;-<span class="st"> </span>tuneR<span class="op">::</span><span class="kw">readWave</span>(<span class="st">&quot;FocalRecordings/FemaleGibbon_1.wav&quot;</span>)</a></code></pre></div>
<p>Now if we run the object it will return some information</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1">GibbonWaveFile</a></code></pre></div>
<pre><code>## 
## Wave Object
##  Number of Samples:      572054
##  Duration (seconds):     12.97
##  Samplingrate (Hertz):   44100
##  Channels (Mono/Stereo): Mono
##  PCM (integer format):   TRUE
##  Bit (8/16/24/32/64):    16</code></pre>
<p>What we see is that the soundfile is ~13 seconds long, was recorded at a sampling rate of 44100 samples per second and has a total of 572054 samples. We can check if that makes sense using the following equation (duration* sampling rate).</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" data-line-number="1">seewave<span class="op">::</span><span class="kw">duration</span>(GibbonWaveFile)<span class="op">*</span><span class="st"> </span>GibbonWaveFile<span class="op">@</span>samp.rate</a></code></pre></div>
<pre><code>## [1] 572054</code></pre>
<p>Now we can plot the waveform from our sound file using the following code:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1">seewave<span class="op">::</span><span class="kw">oscillo</span>(GibbonWaveFile)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>We can also zoom in so that we can actually see the shape of the wave.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1">seewave<span class="op">::</span><span class="kw">oscillo</span>(GibbonWaveFile, <span class="dt">from=</span><span class="fl">0.1</span>, <span class="dt">to=</span><span class="fl">0.2</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>And if we zoom in again we see the wave shape even more.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" data-line-number="1">seewave<span class="op">::</span><span class="kw">oscillo</span>(GibbonWaveFile, <span class="dt">from=</span><span class="fl">0.15</span>, <span class="dt">to=</span><span class="fl">0.2</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>As we learned in class this week, a common way for scientists to study animal sounds is through the use of spectrograms. Here we will plot a spectrogram of a single gibbon call.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" data-line-number="1"><span class="kw">SpectrogramSingle</span>(<span class="dt">sound.file =</span><span class="st">&quot;FocalRecordings/FemaleGibbon_1.wav&quot;</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p>There are many different things you can change when creating a spectrogram. In the above version of the plot there is a lot of space above the gibbon calls, so we will change the frequency range to better visualize the gibbons.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" data-line-number="1"><span class="kw">SpectrogramSingle</span>(<span class="dt">sound.file =</span><span class="st">&quot;FocalRecordings/FemaleGibbon_1.wav&quot;</span>,</a>
<a class="sourceLine" id="cb77-2" data-line-number="2">                  <span class="dt">min.freq =</span> <span class="dv">500</span>,<span class="dt">max.freq=</span><span class="dv">2500</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p>In the code we are using there is also the option to change the color of the spectrogram adding the following code:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" data-line-number="1"><span class="kw">SpectrogramSingle</span>(<span class="dt">sound.file =</span><span class="st">&quot;FocalRecordings/FemaleGibbon_1.wav&quot;</span>,</a>
<a class="sourceLine" id="cb78-2" data-line-number="2">                  <span class="dt">min.freq =</span> <span class="dv">500</span>,<span class="dt">max.freq=</span><span class="dv">2500</span>,</a>
<a class="sourceLine" id="cb78-3" data-line-number="3">                  <span class="dt">Colors =</span> <span class="st">&#39;Colors&#39;</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p>NOTE: Changing the colors doesn’t change how we read the spectrograms,and different people have different preferences.</p>
<p>Now we can plot all of the spectrograms in our FocalRecordings file at once.</p>
<p>NOTE: Use the navigation buttons on the plots tab to move back and forth between the different spectrograms.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" data-line-number="1"><span class="co"># We can tell R to print the spectrograms 2x2 using the code below</span></a>
<a class="sourceLine" id="cb79-2" data-line-number="2"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb79-3" data-line-number="3"></a>
<a class="sourceLine" id="cb79-4" data-line-number="4"><span class="co"># This is the function to create the spectrograms</span></a>
<a class="sourceLine" id="cb79-5" data-line-number="5"><span class="kw">SpectrogramFunction</span>(<span class="dt">input.dir =</span> <span class="st">&quot;FocalRecordings&quot;</span>,<span class="dt">min.freq =</span> <span class="dv">500</span>,<span class="dt">max.freq=</span><span class="dv">2500</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-65-1.png" width="672" /><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-65-2.png" width="672" /><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-65-3.png" width="672" /></p>
<p><em>Question 1.</em> What differences do you notice about gibbon and great argus spectrograms?</p>
<p>Now that you are doing looking at the spectrograms we will clear the space. You can always re-run the code to look at the again.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" data-line-number="1"><span class="kw">graphics.off</span>()</a></code></pre></div>
</div>
<div id="part-2.-visualizing-differences-in-gibbon-and-great-argus-calls" class="section level2 unnumbered">
<h2>Part 2. Visualizing differences in gibbon and great argus calls</h2>
<p>A major question in many different types of behavioral studies is whether there are differences between groups. This is also the case for acoustic data, where researchers may be interested if there are differences between sexes, populations, individuals, or vocalizations emitted in different contexts. Here we will work through a simple example where we will investigate differences in gibbon and argus calls.</p>
<p>The first step that we need to do is called feature extraction. There are many different ways that scientists do this, but the overarching idea is that sound data contains too much redundant information to be used on a model. Computers just don’t have enough power to crunch all those numbers, so we need to identify a meaningful set of features that is smaller than using the while waveform. This is also the case for image processing.</p>
<p>We are going to use a feature extraction method called ‘Mel-frequency cepstral coefficients’. I will not expect you to know any more about them, apart from the fact they are very useful for human speech and bioaccoustics applications.</p>
<p>Below is the function to extract features from our focal recordings</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" data-line-number="1">FeatureDataframe &lt;-<span class="st"> </span><span class="kw">MFCCFunction</span>(<span class="dt">input.dir =</span> <span class="st">&quot;FocalRecordings&quot;</span>)</a></code></pre></div>
<p>In this new dataframe each row represents one gibbon or great argus call. Let’s check the dimensions of this new dataframe.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" data-line-number="1"><span class="kw">dim</span>(FeatureDataframe)</a></code></pre></div>
<pre><code>## [1]  12 178</code></pre>
<p>This shows us that for each of the 10 calls there are 178 features. This is in contrast to a sound file. Let’s check again to remind ourselves.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" data-line-number="1">GibbonWaveFile</a></code></pre></div>
<pre><code>## 
## Wave Object
##  Number of Samples:      572054
##  Duration (seconds):     12.97
##  Samplingrate (Hertz):   44100
##  Channels (Mono/Stereo): Mono
##  PCM (integer format):   TRUE
##  Bit (8/16/24/32/64):    16</code></pre>
<p>This sound file is comprised of 572054 numbers. Now let’s check the first row of our new dataframe which contains the new features for the same gibbon call.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" data-line-number="1"><span class="co"># This isolates the first row.</span></a>
<a class="sourceLine" id="cb86-2" data-line-number="2">FeatureDataframe[<span class="dv">1</span>,] </a></code></pre></div>
<pre><code>##          Class         1         2         3        4         5         6
## 1 FemaleGibbon -4.914312 -16.40678 -4.672827 20.59783 -4.632383 -6.999979
##          7         8        9       10        11        12        13        14
## 1 4.438287 -3.773641 -5.61846 10.73634 0.9757686 -1.163231 -6.800348 -17.70036
##          15       16       17       18       19        20        21        22
## 1 -2.564371 5.702963 8.604349 5.529339 2.561141 -2.507278 -8.423425 -6.229291
##          23        24        25        26      27       28       29       30
## 1 -3.115276 -7.588447 -23.27116 -3.826297 17.3082 8.632006 -1.60833 2.771364
##          31        32        33        34        35        36       37       38
## 1 -3.018685 -13.47489 -5.147027 -6.892077 -12.00958 -21.92954 9.776812 14.48623
##           39       40       41        42      43      44        45        46
## 1 0.08553639 2.275835 4.157477 -15.22412 -8.4252 8.55771 -7.545372 -20.37116
##          47       48        49       50       51        52        53       54
## 1 -9.496601 20.42913 0.1681313 2.009451 4.554415 -16.20235 -2.036649 9.715715
##          55        56       57        58       59        60       61       62
## 1 -1.521847 -4.390747 -23.6537 -1.739798 13.12778 -5.910114 6.569014 6.026896
##          63       64       65        66        67        68       69       70
## 1 -9.226613 -1.68419 4.550749 -5.170068 -10.94638 -20.08074 2.986301 9.424681
##          71       72      73        74         75       76       77        78
## 1 -6.254541 10.38071 -5.0744 -4.867023 -0.4075844 -2.65999 2.784278 -11.88797
##          79       80       81        82       83        84      85       86
## 1 -13.21431 5.279703 8.139582 -5.553872 5.027628 -3.739047 -3.1116 4.341732
##          87      88        89       90        91        92       93       94
## 1 -1.209793 1.00652 -1218.033 -1112.45 -830.5594 -462.4005 25.70725 66.06332
##          95        96       97       98       99       100      101      102
## 1 -5.735883 -36.24788 53.94479 37.60848 3.826036 -1222.493 -1046.01 -770.889
##         103      104      105     106       107       108       109       110
## 1 -393.6294 80.33639 49.16433 5.84342 -92.54861 -126.7318 -115.9133 -78.65571
##         111       112       113       114      115      116      117       118
## 1 -1222.167 -1044.567 -793.9816 -401.6897 87.24976 31.49047 -2.96363 -118.2727
##         119       120       121       122       123       124       125
## 1 -154.4816 -83.69734 -33.83878 -1229.136 -1086.172 -808.4772 -399.4776
##        126      127      128       129     130      131      132       133
## 1 53.89249 11.00474 11.99423 -57.18338 1.68353 85.31662 102.8748 -1239.725
##        134       135       136      137      138       139       140       141
## 1 -1088.64 -803.1513 -479.0124 44.22369 73.85069 -22.86258 -84.05236 -3.588271
##         142      143       144       145       146       147      148      149
## 1 -2.478177 9.528495 -1240.362 -1068.622 -782.7229 -440.9671 63.08211 80.21284
##         150       151       152    153       154       155       156       157
## 1 -46.79594 -82.71886 -40.87362 -75.92 -49.31079 -1285.428 -1091.577 -842.4694
##         158      159     160       161       162      163      164     165
## 1 -460.0004 72.63099 32.0981 -40.61593 -20.85975 31.29035 11.68475 66.2166
##         166       167       168       169     170      171       172       173
## 1 -1225.674 -1065.805 -823.5072 -452.4384 74.0775 24.51663 -33.48887 -13.24513
##        174      175      176      177
## 1 25.57118 3.053292 26.88251 12.97175</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" data-line-number="1"><span class="co"># This tells us how many features we have.</span></a>
<a class="sourceLine" id="cb88-2" data-line-number="2"><span class="kw">ncol</span>(FeatureDataframe[<span class="dv">1</span>,]) </a></code></pre></div>
<pre><code>## [1] 178</code></pre>
<p>OK, now we are ready to do some plotting. If you remember from our earlier lab, the data structure we have here is multivariate, as each call has multiple values associated with it. So we will use the same approach (principal component analysis) to visualize our gibbon and great argus calls.</p>
<p>First we run the principal component analysis</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" data-line-number="1">pca_res &lt;-<span class="st"> </span><span class="kw">prcomp</span>(FeatureDataframe[,<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span>)], <span class="dt">scale. =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>Now we visualize our results</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" data-line-number="1">ggplot2<span class="op">::</span><span class="kw">autoplot</span>(pca_res, <span class="dt">data =</span> FeatureDataframe, </a>
<a class="sourceLine" id="cb91-2" data-line-number="2">         <span class="dt">colour =</span> <span class="st">&#39;Class&#39;</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>What we see in this plot is strong clustering, with the gibbon calls closer to each other than the great argus calls. There is one great argus call that seems to be a bit of an outlier. Let’s check that out using the code below.</p>
<p>NOTE: The code below may take a few minutes to run. If you can’t see the plot well click the ‘zoom’ button on the plot tab</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" data-line-number="1"><span class="kw">BiplotAddSpectrograms</span>(<span class="dt">input.dir.Focal=</span><span class="st">&quot;FocalRecordings&quot;</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>Now that you are done looking at the figure we will clear the space. You can always re-run the code to look at the again.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" data-line-number="1"><span class="kw">graphics.off</span>()</a></code></pre></div>
<p><em>Question 2.</em> Do you see any differences in the spectrogram of the great argus calls that are clustered together and the outlier?</p>
</div>
<div id="part-3.-soundscapes" class="section level2 unnumbered">
<h2>Part 3. Soundscapes</h2>
<p>Now we will do something similar to our investigation of the focal recordings, but using a soundscape example. Here we have 20-sec recordings taken from two different locations (Borneo and Sulawesi) and two different times (06:00 and 18:00). Let’s check what is in the folder.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" data-line-number="1"><span class="kw">list.files</span>(<span class="st">&quot;SoundscapeRecordings&quot;</span>)</a></code></pre></div>
<pre><code>##  [1] &quot;Borneo_Morning_01.wav&quot;   &quot;Borneo_Morning_02.wav&quot;  
##  [3] &quot;Borneo_Morning_03.wav&quot;   &quot;Borneo_Morning_04.wav&quot;  
##  [5] &quot;Borneo_Night_01.wav&quot;     &quot;Borneo_Night_02.wav&quot;    
##  [7] &quot;Borneo_Night_03.wav&quot;     &quot;Borneo_Night_04.wav&quot;    
##  [9] &quot;Sulawesi_Morning_01.wav&quot; &quot;Sulawesi_Morning_02.wav&quot;
## [11] &quot;Sulawesi_Morning_03.wav&quot; &quot;Sulawesi_Morning_04.wav&quot;
## [13] &quot;Sulawesi_Night_01.wav&quot;   &quot;Sulawesi_Night_02.wav&quot;  
## [15] &quot;Sulawesi_Night_03.wav&quot;   &quot;Sulawesi_Night_04.wav&quot;</code></pre>
<p>Now we will create spectrograms for each recording</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb96-2" data-line-number="2"><span class="kw">SpectrogramFunctionSite</span>(<span class="dt">input.dir =</span> <span class="st">&quot;SoundscapeRecordings&quot;</span>,</a>
<a class="sourceLine" id="cb96-3" data-line-number="3">                    <span class="dt">min.freq =</span> <span class="dv">0</span>,<span class="dt">max.freq=</span><span class="dv">20000</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-77-1.png" width="672" /><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-77-2.png" width="672" /><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-77-3.png" width="672" /><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-77-4.png" width="672" /></p>
<p>Now that you are doing looking at the figure we will clear the space. You can always re-run the code to look at the again.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb97-1" data-line-number="1"><span class="kw">graphics.off</span>()</a></code></pre></div>
<p>Now just as above we will do feature extraction of our soundscape recordings. Thiswill convert our dataset into a smaller, much more manageable size.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" data-line-number="1">SoundscapeFeatureDataframe &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb98-2" data-line-number="2"><span class="st">  </span><span class="kw">MFCCFunctionSite</span>(<span class="dt">input.dir =</span> <span class="st">&quot;SoundscapeRecordings&quot;</span>)</a></code></pre></div>
<p>Check the resulting structure of the dataframe to make sure it looks OK.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" data-line-number="1"><span class="kw">dim</span>(SoundscapeFeatureDataframe)</a></code></pre></div>
<pre><code>## [1]  16 177</code></pre>
<p>Now we visualize our results</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" data-line-number="1">pca_res &lt;-<span class="st"> </span><span class="kw">prcomp</span>(SoundscapeFeatureDataframe[,<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span>)], <span class="dt">scale. =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb101-2" data-line-number="2">ggplot2<span class="op">::</span><span class="kw">autoplot</span>(pca_res, <span class="dt">data =</span> SoundscapeFeatureDataframe, </a>
<a class="sourceLine" id="cb101-3" data-line-number="3">         <span class="dt">colour =</span> <span class="st">&#39;Class&#39;</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>It looks like the Borneo_Night sampling period was much different from the rest! Let’s look at a single spectrogram from each sampling location and time.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb102-2" data-line-number="2"><span class="kw">SpectrogramSingle</span>(<span class="dt">sound.file =</span><span class="st">&quot;SoundscapeRecordings/Borneo_Night_01.wav&quot;</span>,</a>
<a class="sourceLine" id="cb102-3" data-line-number="3">                  <span class="dt">min.freq =</span> <span class="dv">0</span>,<span class="dt">max.freq=</span><span class="dv">22000</span>,</a>
<a class="sourceLine" id="cb102-4" data-line-number="4">                  <span class="dt">Colors =</span> <span class="st">&#39;Colors&#39;</span>,<span class="dt">downsample =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb102-5" data-line-number="5"></a>
<a class="sourceLine" id="cb102-6" data-line-number="6"><span class="kw">SpectrogramSingle</span>(<span class="dt">sound.file =</span><span class="st">&quot;SoundscapeRecordings/Borneo_Morning_01.wav&quot;</span>,</a>
<a class="sourceLine" id="cb102-7" data-line-number="7">                  <span class="dt">min.freq =</span> <span class="dv">0</span>,<span class="dt">max.freq=</span><span class="dv">22000</span>,</a>
<a class="sourceLine" id="cb102-8" data-line-number="8">                  <span class="dt">Colors =</span> <span class="st">&#39;Colors&#39;</span>,<span class="dt">downsample =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb102-9" data-line-number="9"></a>
<a class="sourceLine" id="cb102-10" data-line-number="10"><span class="kw">SpectrogramSingle</span>(<span class="dt">sound.file =</span><span class="st">&quot;SoundscapeRecordings/Sulawesi_Night_01.wav&quot;</span>,</a>
<a class="sourceLine" id="cb102-11" data-line-number="11">                  <span class="dt">min.freq =</span> <span class="dv">0</span>,<span class="dt">max.freq=</span><span class="dv">22000</span>,</a>
<a class="sourceLine" id="cb102-12" data-line-number="12">                  <span class="dt">Colors =</span> <span class="st">&#39;Colors&#39;</span>,<span class="dt">downsample =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb102-13" data-line-number="13"></a>
<a class="sourceLine" id="cb102-14" data-line-number="14"><span class="kw">SpectrogramSingle</span>(<span class="dt">sound.file =</span><span class="st">&quot;SoundscapeRecordings/Sulawesi_Morning_01.wav&quot;</span>,</a>
<a class="sourceLine" id="cb102-15" data-line-number="15">                  <span class="dt">min.freq =</span> <span class="dv">0</span>,<span class="dt">max.freq=</span><span class="dv">22000</span>,</a>
<a class="sourceLine" id="cb102-16" data-line-number="16">                  <span class="dt">Colors =</span> <span class="st">&#39;Colors&#39;</span>,<span class="dt">downsample =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p><em>Question 3</em>. You can listen to example sound files on the Canvas page. Between looking at the spectrograms and listening to the sound files what do you think are the main differences between the different locations and times?</p>
</div>
<div id="part-4.-now-it-is-time-to-analyze-the-data-you-collected-for-this-weeks-field-lab." class="section level2 unnumbered">
<h2>Part 4. Now it is time to analyze the data you collected for this week’s field lab.</h2>
<p>Upload your sound files into either the ‘MyFocalRecordings’ folder or the ’MySoundscapeRecordings’folder and run the code below.</p>
<p>NOTE: Make sure to delete the existing files before you add your own!</p>
<div id="part-4a.-your-focal-recordings" class="section level3">
<h3><span class="header-section-number">3.0.1</span> Part 4a. Your focal recordings</h3>
<p>First lets visualize the spectrograms. You may want to change the frequency settings depending on the frequency range of your focal animals.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" data-line-number="1"><span class="co"># We can tell R to print the spectrograms 2x2 using the code below</span></a>
<a class="sourceLine" id="cb103-2" data-line-number="2"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb103-3" data-line-number="3"></a>
<a class="sourceLine" id="cb103-4" data-line-number="4"><span class="co"># This is the function to create the spectrograms</span></a>
<a class="sourceLine" id="cb103-5" data-line-number="5"><span class="kw">SpectrogramFunction</span>(<span class="dt">input.dir =</span> <span class="st">&quot;MyFocalRecordings&quot;</span>,<span class="dt">min.freq =</span> <span class="dv">200</span>,<span class="dt">max.freq=</span><span class="dv">2000</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>Here is the function to extract the features. Again, based on the frequency range of your focal recordings you may want to change the frequency settings.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" data-line-number="1">MyFeatureDataFrame &lt;-<span class="st"> </span><span class="kw">MFCCFunction</span>(<span class="dt">input.dir =</span> <span class="st">&quot;MyFocalRecordings&quot;</span>,<span class="dt">min.freq =</span> <span class="dv">200</span>,<span class="dt">max.freq=</span><span class="dv">2000</span>)</a></code></pre></div>
<p>Then we run the principal component analysis</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" data-line-number="1">pca_res &lt;-<span class="st"> </span><span class="kw">prcomp</span>(MyFeatureDataFrame[,<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span>)], <span class="dt">scale. =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>Now we visualize our results</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" data-line-number="1">ggplot2<span class="op">::</span><span class="kw">autoplot</span>(pca_res, <span class="dt">data =</span> MyFeatureDataFrame,</a>
<a class="sourceLine" id="cb106-2" data-line-number="2">         <span class="dt">colour =</span> <span class="st">&#39;Class&#39;</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
</div>
<div id="part-4b.-soundscape-recordings" class="section level3">
<h3><span class="header-section-number">3.0.2</span> Part 4b. Soundscape recordings</h3>
<p>First lets visualize the spectrograms. You probably don’t want to change the frequency settings for this.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" data-line-number="1"><span class="co"># We can tell R to print the spectrograms 2x2 using the code below</span></a>
<a class="sourceLine" id="cb107-2" data-line-number="2"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb107-3" data-line-number="3"></a>
<a class="sourceLine" id="cb107-4" data-line-number="4"><span class="co"># This is the function to create the spectrograms</span></a>
<a class="sourceLine" id="cb107-5" data-line-number="5"><span class="kw">SpectrogramFunction</span>(<span class="dt">input.dir =</span> <span class="st">&quot;MySoundscapeRecordings&quot;</span>,<span class="dt">min.freq =</span> <span class="dv">200</span>,<span class="dt">max.freq=</span><span class="dv">10000</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<p>Then we extract the features, which in this case are the MFCCs.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" data-line-number="1">MySoundscapeFeatureDataframe &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb108-2" data-line-number="2"><span class="st">  </span><span class="kw">MFCCFunctionSite</span>(<span class="dt">input.dir =</span> <span class="st">&quot;MySoundscapeRecordings&quot;</span>,<span class="dt">min.freq =</span> <span class="dv">200</span>,<span class="dt">max.freq=</span><span class="dv">10000</span>)</a></code></pre></div>
<p>Check the resulting structure of the dataframe to make sure it looks OK.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" data-line-number="1"><span class="kw">dim</span>(MySoundscapeFeatureDataframe)</a></code></pre></div>
<p>Now we visualize our results</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" data-line-number="1">pca_res &lt;-<span class="st"> </span><span class="kw">prcomp</span>(MySoundscapeFeatureDataframe[,<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span>)], <span class="dt">scale. =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb110-2" data-line-number="2">ggplot2<span class="op">::</span><span class="kw">autoplot</span>(pca_res, <span class="dt">data =</span> MySoundscapeFeatureDataframe, </a>
<a class="sourceLine" id="cb110-3" data-line-number="3">         <span class="dt">colour =</span> <span class="st">&#39;Class&#39;</span>)</a></code></pre></div>
<p><img src="behaviouR-R-package-tutorials_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p><em>Question 4</em>. Do you see evidence of clustering in either your focal recordings or soundscape recordings?</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lab-2-activity-budgets-and-ethograms.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lab-4-vigilance-behavior.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/03-Lab-3-Analyzing-Acoustic-Data.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["behaviouR-R-package-tutorials.pdf", "behaviouR-R-package-tutorials.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
